id: tx-pool-check
name: "Check transaction pool"
timeout: 30m
disable: false
config:
  walletPrivkey: ""
  # validatorPairNames: []
  # minBlobCount: 3
tasks:
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 1.000 transactions"
  config:
    nonce: 0
    txCount: 1000
    measureInterval: 100
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 1.000 transactions"
  config:
    nonce: 1000
    txCount: 1000
    measureInterval: 100
    expectedLatency: 5000
    failOnHighLatency: true
  configVars:
    privateKey: "walletPrivkey"
