id: tx-pool-check-short
name: "Check transaction pool short"
timeout: 30m
disable: false
config:
  walletPrivkey: ""
tasks:
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 10.000 transactions"
  timeout: 30m
  config:
    tps: 2000
    durationS: 5
    logInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 30m
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 10.000 transactions"
  timeout: 30m
  config:
    tps: 2000
    durationS: 5
    logInterval: 1000
  configVars:
    privateKey: "walletPrivkey"