id: tx-pool-check
name: "Check transaction pool"
timeout: 30m
disable: false
config:
  walletPrivkey: ""
tasks:
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 10.000 transactions"
  timeout: 30m
  config:
    qps: 20000
    measureInterval: 2000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 30m
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 10.000 transactions"
  timeout: 30m
  config:
    txCount: 20000
    measureInterval: 2000
    highLatency: 7000
    failOnHighLatency: true
  configVars:
    privateKey: "walletPrivkey"
