id: tx-pool-check
name: "Check transaction pool"
timeout: 30m
disable: false
config:
  walletPrivkey: ""
  # validatorPairNames: []
  # minBlobCount: 3
tasks:
- name: tx_pool_check
  config:
    txCount: 15000
    measureInterval: 500
    expectedLatency: 500
    failOnHighLatency: true
    clientPattern: ""
    excludeClientPattern: ""
  configVars:
    privateKey: "walletPrivkey"