id: tx-pool-check
name: "Check transaction pool"
timeout: 2h
disable: false
config:
  walletPrivkey: ""
tasks:
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 1.000 transactions"
  timeout: 5m
  config:
    tps: 1000
    duration_s: 10
    measureInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 5m
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  timeout: 5m
  title: "Check transaction pool throughput with 1.000 transactions in one second"
  config:
    tps: 1000
    duration_s: 10
    measureInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
# - name: tx_pool_clean
#   title: "Clean transaction pool"
#   timeout: 5m
#   config:
#     waitTime: 5
# - name: tx_pool_latency_analysis
#   title: "Check transaction pool latency with 10.000 transactions"
#   timeout: 10m
#   config:
#     txCount: 10000
#     measureInterval: 1000
#     highLatency: 5000
#     failOnHighLatency: true
#   configVars:
#     privateKey: "walletPrivkey"
# - name: tx_pool_clean
#   title: "Clean transaction pool"
#   timeout: 10m
#   config:
#     waitTime: 5
# - name: tx_pool_throughput_analysis
#   title: "Check transaction pool throughput with 10.000 transactions in one second"
#   timeout: 10m
#   config:
#     qps: 10000
#     measureInterval: 1000
#   configVars:
#     privateKey: "walletPrivkey"
# - name: tx_pool_clean
#   title: "Clean transaction pool"
#   timeout: 10m
#   config:
#     waitTime: 5
# - name: tx_pool_latency_analysis
#   title: "Check transaction pool latency with 15.000 transactions"
#   timeout: 30m
#   config:
#     txCount: 15000
#     measureInterval: 1500
#     highLatency: 7000
#     failOnHighLatency: true
#   configVars:
#     privateKey: "walletPrivkey"
# - name: tx_pool_clean
#   title: "Clean transaction pool"
#   timeout: 30m
#   config:
#     waitTime: 5
# - name: tx_pool_throughput_analysis
#   timeout: 30m
#   title: "Check transaction pool throughput with 15.000 transactions in one second"
#   config:
#     qps: 15000
#     measureInterval: 1500
#   configVars:
#     privateKey: "walletPrivkey"
